// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Segmentation.Infrastructure.Persistence;

#nullable disable

namespace Segmentation.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525122607_UnifiedFarmerContractKpiAndPerKpiScopes")]
    partial class UnifiedFarmerContractKpiAndPerKpiScopes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Segmentation.Domain.Entities.CropSeason", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CropSeasons", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.CultureType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("CultureTypes", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.EsgIrregularityKpi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CropSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CultureTypeCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("IrregularityTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CropSeasonId");

                    b.HasIndex("CultureTypeCode");

                    b.HasIndex("IrregularityTypeId");

                    b.HasIndex("FarmerId", "CropSeasonId", "CultureTypeCode", "IrregularityTypeId")
                        .IsUnique();

                    b.ToTable("EsgIrregularityKpis", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.Farmer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NonExclusiveFarmer")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Farmers", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.FarmerCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FarmerClusters", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.FarmerClusterFarmer", b =>
                {
                    b.Property<Guid>("ClusterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("TEXT");

                    b.HasKey("ClusterId", "FarmerId");

                    b.HasIndex("FarmerId");

                    b.ToTable("FarmerClusterFarmers", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.FarmerContractKpi", b =>
                {
                    b.Property<Guid>("FarmerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CropSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CultureTypeCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractedAmountKg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveredAmountKg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveredPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HadNtrm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HadQualityMixture")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HaveDebt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Iqs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NativeForestPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NonExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReforestationPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scale")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelfFundingPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Yield")
                        .HasColumnType("INTEGER");

                    b.HasKey("FarmerId", "CropSeasonId", "CultureTypeCode");

                    b.HasIndex("CropSeasonId");

                    b.HasIndex("CultureTypeCode");

                    b.ToTable("FarmerContractKpis", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.FarmerSegmentation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CropSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EsgScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FinancialScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoyaltyScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NonExclusiveFarmer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualityScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScaleScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentationConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SegmentationConfigurationSegmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TechnologiesScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YieldScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CropSeasonId");

                    b.HasIndex("SegmentationConfigurationId");

                    b.HasIndex("SegmentationConfigurationSegmentId");

                    b.HasIndex("FarmerId", "CropSeasonId")
                        .IsUnique();

                    b.ToTable("FarmerSegmentations", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.FinancialSelfFundingRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CropSeasonAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Maximum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minimum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SegmentationConfigurationCultureTypeId");

                    b.ToTable("FinancialSelfFundingRanges", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.IrregularityTypeCatalog", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IrregularityTypes", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.LoyaltyHistoricalVolumeRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumDeliveryAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumDeliveryAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SegmentationConfigurationCultureTypeId");

                    b.ToTable("LoyaltyHistoricalVolumeRanges", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.LoyaltySeasonQuantityRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryCropSeasonAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumDeliveryAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumDeliveryAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantingCropSeasonAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SegmentationConfigurationCultureTypeId");

                    b.ToTable("LoyaltySeasonQuantityRanges", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.QualityIqsRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CropSeasonAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Maximum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minimum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SegmentationConfigurationCultureTypeId");

                    b.ToTable("QualityIqsRanges", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.ScaleRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CropSeasonAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Maximum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minimum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SegmentationConfigurationCultureTypeId");

                    b.ToTable("ScaleRanges", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SegmentationConfigurations", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationCultureType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CultureTypeCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentationConfigurationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CultureTypeCode");

                    b.HasIndex("SegmentationConfigurationId", "CultureTypeCode")
                        .IsUnique();

                    b.ToTable("SegmentationConfigurationCultureTypes", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationCultureTypeSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RangeMin")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SegmentationSegmentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SegmentationSegmentId");

                    b.HasIndex("SegmentationConfigurationCultureTypeId", "SegmentationSegmentId")
                        .IsUnique();

                    b.ToTable("SegmentationConfigurationCultureTypeSegments", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationEsg", b =>
                {
                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NativeForestMaximumScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NativeForestScorePerPercentualPoint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReforestationMaximumScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReforestationScorePerPercentualPoint")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Relevance")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("SegmentationConfigurationCultureTypeId");

                    b.ToTable("SegmentationConfigurationEsgs", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationEsgIrregularityScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("IrregularityTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IrregularityTypeId");

                    b.HasIndex("SegmentationConfigurationCultureTypeId", "IrregularityTypeId")
                        .IsUnique();

                    b.ToTable("SegmentationConfigurationEsgIrregularityScores", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationFinancial", b =>
                {
                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebtScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Relevance")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("SegmentationConfigurationCultureTypeId");

                    b.ToTable("SegmentationConfigurationFinancials", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationLoyalty", b =>
                {
                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Relevance")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("SegmentationConfigurationCultureTypeId");

                    b.ToTable("SegmentationConfigurationLoyalties", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationQuality", b =>
                {
                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MixtureScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NtrmScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Relevance")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("SegmentationConfigurationCultureTypeId");

                    b.ToTable("SegmentationConfigurationQualities", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationScale", b =>
                {
                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Relevance")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("SegmentationConfigurationCultureTypeId");

                    b.ToTable("SegmentationConfigurationScales", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationTechnology", b =>
                {
                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Relevance")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("SegmentationConfigurationCultureTypeId");

                    b.ToTable("SegmentationConfigurationTechnologies", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationTechnologyScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyId");

                    b.HasIndex("SegmentationConfigurationCultureTypeId", "TechnologyId")
                        .IsUnique();

                    b.ToTable("SegmentationConfigurationTechnologyScores", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationYield", b =>
                {
                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Relevance")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("SegmentationConfigurationCultureTypeId");

                    b.ToTable("SegmentationConfigurationYields", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BankDepositDiscount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnlyExclusiveFarmer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SegmentationConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TobaccoDiscount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SegmentationConfigurationId");

                    b.ToTable("SegmentationSegments", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationSimulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CropSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentationConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SimulationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CropSeasonId");

                    b.HasIndex("SegmentationConfigurationId");

                    b.ToTable("SegmentationSimulations", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationSimulationFarmer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CultureTypeCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("EsgScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FinancialScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNewFarmer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoyaltyScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NonExclusiveFarmer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualityScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScaleScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SegmentationConfigurationSegmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SegmentationSimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TechnologiesScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YieldScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.HasIndex("SegmentationConfigurationSegmentId");

                    b.HasIndex("SegmentationSimulationId", "FarmerId")
                        .IsUnique();

                    b.ToTable("SegmentationSimulationFarmers", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationSimulationKpiScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("KpiKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SegmentationSimulationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueAggregation")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SegmentationSimulationId", "KpiKind")
                        .IsUnique();

                    b.ToTable("SegmentationSimulationKpiScopes", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationSimulationKpiScopeSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CropSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentationSimulationKpiScopeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CropSeasonId");

                    b.HasIndex("SegmentationSimulationKpiScopeId", "CropSeasonId")
                        .IsUnique();

                    b.ToTable("SegmentationSimulationKpiScopeSeasons", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.TechnologiesKpi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CropSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CultureTypeCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CropSeasonId");

                    b.HasIndex("CultureTypeCode");

                    b.HasIndex("TechnologyId");

                    b.HasIndex("FarmerId", "CropSeasonId", "CultureTypeCode", "TechnologyId")
                        .IsUnique();

                    b.ToTable("TechnologiesKpis", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.TechnologyCatalog", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Technologies", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.YieldRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CropSeasonAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Maximum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minimum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SegmentationConfigurationCultureTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SegmentationConfigurationCultureTypeId");

                    b.ToTable("YieldRanges", (string)null);
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.EsgIrregularityKpi", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.CropSeason", "CropSeason")
                        .WithMany()
                        .HasForeignKey("CropSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.CultureType", "CultureType")
                        .WithMany()
                        .HasForeignKey("CultureTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.Farmer", "Farmer")
                        .WithMany("EsgIrregularityKpis")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.IrregularityTypeCatalog", "IrregularityType")
                        .WithMany("EsgIrregularityKpis")
                        .HasForeignKey("IrregularityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CropSeason");

                    b.Navigation("CultureType");

                    b.Navigation("Farmer");

                    b.Navigation("IrregularityType");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.FarmerClusterFarmer", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.FarmerCluster", "Cluster")
                        .WithMany("Farmers")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.Farmer", "Farmer")
                        .WithMany("ClusterLinks")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.FarmerContractKpi", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.CropSeason", "CropSeason")
                        .WithMany()
                        .HasForeignKey("CropSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.CultureType", "CultureType")
                        .WithMany()
                        .HasForeignKey("CultureTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.Farmer", "Farmer")
                        .WithMany("ContractKpis")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropSeason");

                    b.Navigation("CultureType");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.FarmerSegmentation", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.CropSeason", "CropSeason")
                        .WithMany()
                        .HasForeignKey("CropSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.Farmer", "Farmer")
                        .WithMany("Segmentations")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfiguration", "SegmentationConfiguration")
                        .WithMany()
                        .HasForeignKey("SegmentationConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.SegmentationSegment", "Segment")
                        .WithMany("FarmerSegmentations")
                        .HasForeignKey("SegmentationConfigurationSegmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CropSeason");

                    b.Navigation("Farmer");

                    b.Navigation("Segment");

                    b.Navigation("SegmentationConfiguration");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.FinancialSelfFundingRange", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationFinancial", "Financial")
                        .WithMany("SelfFundingRanges")
                        .HasForeignKey("SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Financial");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.LoyaltyHistoricalVolumeRange", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationLoyalty", "Loyalty")
                        .WithMany("HistoricalVolumeRanges")
                        .HasForeignKey("SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loyalty");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.LoyaltySeasonQuantityRange", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationLoyalty", "Loyalty")
                        .WithMany("SeasonQuantityRanges")
                        .HasForeignKey("SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loyalty");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.QualityIqsRange", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationQuality", "Quality")
                        .WithMany("IqsRanges")
                        .HasForeignKey("SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quality");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.ScaleRange", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationScale", "Scale")
                        .WithMany("Ranges")
                        .HasForeignKey("SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scale");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationCultureType", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.CultureType", "CultureType")
                        .WithMany()
                        .HasForeignKey("CultureTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfiguration", "SegmentationConfiguration")
                        .WithMany("CultureTypes")
                        .HasForeignKey("SegmentationConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CultureType");

                    b.Navigation("SegmentationConfiguration");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationCultureTypeSegment", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationCultureType", "CultureType")
                        .WithMany("CultureTypeSegments")
                        .HasForeignKey("SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.SegmentationSegment", "Segment")
                        .WithMany("CultureTypeSegments")
                        .HasForeignKey("SegmentationSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CultureType");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationEsg", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationCultureType", "CultureType")
                        .WithOne("Esg")
                        .HasForeignKey("Segmentation.Domain.Entities.SegmentationConfigurationEsg", "SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CultureType");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationEsgIrregularityScore", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.IrregularityTypeCatalog", "IrregularityType")
                        .WithMany("ConfigurationScores")
                        .HasForeignKey("IrregularityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationEsg", "EsgBlock")
                        .WithMany("IrregularityScores")
                        .HasForeignKey("SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EsgBlock");

                    b.Navigation("IrregularityType");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationFinancial", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationCultureType", "CultureType")
                        .WithOne("Financial")
                        .HasForeignKey("Segmentation.Domain.Entities.SegmentationConfigurationFinancial", "SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CultureType");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationLoyalty", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationCultureType", "CultureType")
                        .WithOne("Loyalty")
                        .HasForeignKey("Segmentation.Domain.Entities.SegmentationConfigurationLoyalty", "SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CultureType");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationQuality", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationCultureType", "CultureType")
                        .WithOne("Quality")
                        .HasForeignKey("Segmentation.Domain.Entities.SegmentationConfigurationQuality", "SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CultureType");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationScale", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationCultureType", "CultureType")
                        .WithOne("Scale")
                        .HasForeignKey("Segmentation.Domain.Entities.SegmentationConfigurationScale", "SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CultureType");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationTechnology", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationCultureType", "CultureType")
                        .WithOne("Technology")
                        .HasForeignKey("Segmentation.Domain.Entities.SegmentationConfigurationTechnology", "SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CultureType");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationTechnologyScore", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationTechnology", "TechnologyBlock")
                        .WithMany("TechnologyScores")
                        .HasForeignKey("SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.TechnologyCatalog", "Technology")
                        .WithMany("ConfigurationScores")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Technology");

                    b.Navigation("TechnologyBlock");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationYield", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationCultureType", "CultureType")
                        .WithOne("Yield")
                        .HasForeignKey("Segmentation.Domain.Entities.SegmentationConfigurationYield", "SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CultureType");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationSegment", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfiguration", "SegmentationConfiguration")
                        .WithMany("Segments")
                        .HasForeignKey("SegmentationConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SegmentationConfiguration");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationSimulation", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.CropSeason", "CropSeason")
                        .WithMany()
                        .HasForeignKey("CropSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfiguration", "SegmentationConfiguration")
                        .WithMany("Simulations")
                        .HasForeignKey("SegmentationConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CropSeason");

                    b.Navigation("SegmentationConfiguration");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationSimulationFarmer", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.Farmer", "Farmer")
                        .WithMany("SimulationResults")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.SegmentationSegment", "Segment")
                        .WithMany("SimulationFarmers")
                        .HasForeignKey("SegmentationConfigurationSegmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Segmentation.Domain.Entities.SegmentationSimulation", "SegmentationSimulation")
                        .WithMany("Farmers")
                        .HasForeignKey("SegmentationSimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");

                    b.Navigation("Segment");

                    b.Navigation("SegmentationSimulation");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationSimulationKpiScope", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationSimulation", "SegmentationSimulation")
                        .WithMany("KpiScopes")
                        .HasForeignKey("SegmentationSimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SegmentationSimulation");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationSimulationKpiScopeSeason", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.CropSeason", "CropSeason")
                        .WithMany()
                        .HasForeignKey("CropSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.SegmentationSimulationKpiScope", "KpiScope")
                        .WithMany("Seasons")
                        .HasForeignKey("SegmentationSimulationKpiScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropSeason");

                    b.Navigation("KpiScope");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.TechnologiesKpi", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.CropSeason", "CropSeason")
                        .WithMany()
                        .HasForeignKey("CropSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.CultureType", "CultureType")
                        .WithMany()
                        .HasForeignKey("CultureTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.Farmer", "Farmer")
                        .WithMany("TechnologiesKpis")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Segmentation.Domain.Entities.TechnologyCatalog", "Technology")
                        .WithMany("TechnologiesKpis")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CropSeason");

                    b.Navigation("CultureType");

                    b.Navigation("Farmer");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.YieldRange", b =>
                {
                    b.HasOne("Segmentation.Domain.Entities.SegmentationConfigurationYield", "Yield")
                        .WithMany("Ranges")
                        .HasForeignKey("SegmentationConfigurationCultureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yield");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.Farmer", b =>
                {
                    b.Navigation("ClusterLinks");

                    b.Navigation("ContractKpis");

                    b.Navigation("EsgIrregularityKpis");

                    b.Navigation("Segmentations");

                    b.Navigation("SimulationResults");

                    b.Navigation("TechnologiesKpis");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.FarmerCluster", b =>
                {
                    b.Navigation("Farmers");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.IrregularityTypeCatalog", b =>
                {
                    b.Navigation("ConfigurationScores");

                    b.Navigation("EsgIrregularityKpis");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfiguration", b =>
                {
                    b.Navigation("CultureTypes");

                    b.Navigation("Segments");

                    b.Navigation("Simulations");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationCultureType", b =>
                {
                    b.Navigation("CultureTypeSegments");

                    b.Navigation("Esg");

                    b.Navigation("Financial");

                    b.Navigation("Loyalty");

                    b.Navigation("Quality");

                    b.Navigation("Scale");

                    b.Navigation("Technology");

                    b.Navigation("Yield");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationEsg", b =>
                {
                    b.Navigation("IrregularityScores");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationFinancial", b =>
                {
                    b.Navigation("SelfFundingRanges");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationLoyalty", b =>
                {
                    b.Navigation("HistoricalVolumeRanges");

                    b.Navigation("SeasonQuantityRanges");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationQuality", b =>
                {
                    b.Navigation("IqsRanges");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationScale", b =>
                {
                    b.Navigation("Ranges");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationTechnology", b =>
                {
                    b.Navigation("TechnologyScores");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationConfigurationYield", b =>
                {
                    b.Navigation("Ranges");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationSegment", b =>
                {
                    b.Navigation("CultureTypeSegments");

                    b.Navigation("FarmerSegmentations");

                    b.Navigation("SimulationFarmers");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationSimulation", b =>
                {
                    b.Navigation("Farmers");

                    b.Navigation("KpiScopes");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.SegmentationSimulationKpiScope", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("Segmentation.Domain.Entities.TechnologyCatalog", b =>
                {
                    b.Navigation("ConfigurationScores");

                    b.Navigation("TechnologiesKpis");
                });
#pragma warning restore 612, 618
        }
    }
}
